version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_dev
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "CarDB123*"
      ACCEPT_EULA: "Y"
    restart: unless-stopped
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
